
#  __    _____ _____ _____ 
# |  |  |     |  _  |     |
# |  |__| | | |     |  |  |
# |_____|_|_|_|__|__|_____|
# 
# This file holds configuration for the lmao marker detector
# Notes:
#  - Units of measurement must be expressed explicitly (for example angle must be "<ANGLE> rad" or "<ANGLE> deg")

detector:
  type: static

gimbal:
  position:
    forward: 0 m
    right:   0 m
    up:      0 m
  rotation:
    roll:   0 deg
    pitch:  0 deg
    yaw:    0 deg

camera:
  type: airsim
  horizontal_fov: 90 deg
  vertical_fov: 67.5 deg

live_view:
  type: none

communication:
  telemetry:
    type: mavlink
    address: udpin:0.0.0.0:14550
  mission:
    type: none
